### ISSUE TITLE
Startpage 3 - mobile

### ISSUE THREAD

**Issue by darktweek** [grtcdr/startpages#1]
Hi!
Very interesting project.
Is it possible to make a responsive version for mobile?

Thanks.

**Comment by grtcdr** [comment]
I'll give it a try and keep you up to speed if I encounter any issues.
Would you like the startpages to be extensions on mobile as well?

**Comment by darktweek** [comment]
No I host on my server 😁

**Comment by grtcdr** [comment]
After some research and a lot of trial and error, I sort of lost hope in trying to implement your request, I'm having all sorts of issues.
I'll keep trying but I can't promise anything as mobile support is new territory for me, if you are however experienced with web development, I would very much appreciate it if you contributed to the project.

**Comment by darktweek** [comment]
It's ok. I have 0 skill for coding. Sorry I can't help you for this.

**Comment by grtcdr** [comment]
I'll close down the issue for now. If at any point I figure what it out, I will roll out the changes!
