### ISSUE TITLE
web-ext fix + scrolling

### ISSUE THREAD

**Issue by aryakaul** [grtcdr/startpages#2]
Hello! Thank you for making this! As someone with 0 javascript experience, I'm really enjoying tweaking and looking through the code. 

Two things:
1. I think you should include `.web-extension-id` in your `.gitignore`, when it's present the web-ext command will fail with the error `You do not own this extension`. Removing that file and rerunning the command fixes the issue.
2. Currently, I don't think it's possible to scroll down if the window is too small to display the full cards (I'm using startpage_3) - any idea how one could fix that?

Cheers!

**Comment by grtcdr** [comment]
Hi, thanks for the feedback. love seeing people enjoy these as it started as a fun little challenge at first!
I will definitely consider your request next time I push to the repository, and as for the scrolling, I just tried that as well and it might have something to with the "overflow" property as I have it hidden for aesthetic purposes, try:
`overflow: visible`
and see if that helps solve your issue as I believe it did for me.

**Comment by aryakaul** [comment]
Ah thank you! Changing `overflow` enabled scrolling
