### ISSUE TITLE
Also override homepage

### ISSUE THREAD

**Issue by h-marti** [grtcdr/startpages#4]
Hi!

Is there a possibility to also override the browser homepage ?

Here is my `manifest.json`

`{
    "manifest_version": 2,
    "name": "Startpage",
    "version": "1.3",
    "description": "Custom new tab startpage",
    "chrome_settings_overrides" : {
      "homepage": "startpage.html"
    },
    "chrome_url_overrides": {
      "newtab": "startpage.html"
    },
    "content_security_policy": "script-src 'self'; script-src 'unsafe-inline'; object-src 'self';"
//    "homepage_url": "startpage.html"
}`

If I uncomment the homepage_url property the extension won't sign.

**Comment by grtcdr** [comment]
I'm not sure, but I'll take a look at mozilla's docs, there's quality stuff in there.

**Comment by h-marti** [comment]
Okay so after rebuilding the extension without uncommenting the "homepage_url" property it just worked out of the blue!

I guess the correct property to use here is `"chrome_settings_overrides" : { "homepage": "startpage.html" }`.
At least it worked for me..
