### ISSUE TITLE
Username error

### ISSUE THREAD

**Issue by satyamm009** [grtcdr/startpages#5]
Username doesn't change. 
![image](https://user-images.githubusercontent.com/74500169/125167797-f330d900-e1bf-11eb-826d-8d0317e8b9e7.png)

**Comment by grtcdr** [comment]
You have to change it manually in `script.js`:

```javascript
var username = "grtcdr"; // Place your username here, then reload the page.
```

**Comment by satyamm009** [comment]
Also how to set startpage as homepage? It has been set as New tab page

**Comment by grtcdr** [comment]
See [this](https://github.com/grtcdr/startpages/issues/4), h-marti found a way to do this.
