### ISSUE TITLE
Error in 'web-ext sign' command

### ISSUE THREAD

**Issue by KongThePirate** [grtcdr/startpages#7]
My command looks like this (fake details of course) web-ext sign --api-key=user:12345678:910 --api-secret 38219832a83218b8238120, and it sends the error 'Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v4/addons/' out.

**Comment by grtcdr** [comment]
Try wrapping it in `${}` like so:
```
web-ext sign --api-key ${key} --api-secret ${secret}
```

**Comment by KongThePirate** [comment]
Now I simply get a zsh: bad substitution error

**Comment by KongThePirate** [comment]
This is giving me now a ''zsh: bad substitution error''

**Comment by grtcdr** [comment]
What did you type in the command-line?

```
web-ext sign --api-key ${foo} --api-secret ${bar}
```

Doesn't give me a zsh error.

**Comment by KongThePirate** [comment]
I typed that except with the values inside, if i just put foo and bar like you did I don't get the errors.

**Comment by grtcdr** [comment]
That's really weird, I'm not really an expert on mozilla's toolings, but if I were you, I'd just create another token and try again.

**Comment by KongThePirate** [comment]
I have found the answer. Took a lot of retries, and it's a weird one. It wasn't the ${} and actually that is completely unnecessary. I didn't have my system clock set to automatic and that's what caused the error.

**Comment by grtcdr** [comment]
> I didn't have my system clock set to automatic and that's what caused the error.

Oh, that makes a lot of sense.
